default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['USER'] %>

development:
  <<: *default
  database: herd_fest_development
  pool: 5

test:
  <<: *default
  database: herd_fest_test
  pool: 1

production:
  <<: *default
  pool: <%= ENV['DB_POOL'] %>
  host: <%= ENV['DATA_BASE_URL'] %>
  database: herd_fest_production
